/* =====================================================================
   TIME-LIMITED DEALS — rendering only
   ---------------------------------------------------------------------
   You do NOT edit this file anymore. Deals are managed entirely from
   your POS, saved into the same Firestore document your menu already
   reads from (settings/main.deals). js/menu.js reads that live and
   calls window.renderDeals() below whenever it changes — same pattern
   as how your live menu already works.

   Expected shape of each item in settings/main.deals (set by the POS):
     {
       active: true/false,
       image: "<uploaded photo URL>",
       productId: "<the product's id>"   // preferred — exact & stable
       // OR, if the POS doesn't have an id handy:
       itemName: "<exact product name>"
     }

   BEHAVIOR (automatic, based on how many deals have active: true):
     • 0 active   -> section hidden completely.
     • 1 active   -> just that image + its Order Now button show. No
                     dots, nothing rotates — fully static.
     • 2+ active  -> images crossfade automatically, dots appear to
                     jump between them.
     • Clicking the image OR the Order Now button scrolls straight to
       that product in the Menu section and highlights it.
===================================================================== */

window.renderDeals = function (deals) {
  const active = (deals || []).filter(function (d) { return d.active; });
  const section = document.getElementById("dealsSection");
  const slider = document.getElementById("dealsSlider");
  const dotsWrap = document.getElementById("dealsDots");
  if (!section || !slider) return;

  if (active.length === 0) {
    section.style.display = "none";
    slider.innerHTML = "";
    dotsWrap.innerHTML = "";
    dotsWrap.classList.remove("show");
    return;
  }
  section.style.display = "block";

  slider.innerHTML = active.map(function (d, i) {
    const targetRef = d.productId || d.itemName || "";
    const isActive = i === 0 ? " active" : "";
    return (
      '<img src="' + escapeAttr(d.image || "") + '" alt="Deal"' +
      ' class="' + isActive.trim() + '" data-target="' + escapeAttr(targetRef) + '">' +
      '<button type="button" class="deal-order-btn' + isActive + '" data-target="' + escapeAttr(targetRef) + '">' +
        'Order Now <i class="fas fa-arrow-right"></i>' +
      '</button>'
    );
  }).join("");

  const imgs = slider.querySelectorAll("img");
  const btns = slider.querySelectorAll(".deal-order-btn");

  function goToProduct(ref) {
    if (typeof window.scrollToMenuItem === "function") {
      window.scrollToMenuItem(ref);
    }
  }
  imgs.forEach(function (img) {
    img.addEventListener("click", function () { goToProduct(img.getAttribute("data-target")); });
  });
  btns.forEach(function (btn) {
    btn.addEventListener("click", function () { goToProduct(btn.getAttribute("data-target")); });
  });

  // Only one active deal: leave it fully static, no dots, no rotation.
  if (active.length <= 1) {
    dotsWrap.classList.remove("show");
    dotsWrap.innerHTML = "";
    return;
  }

  // Two or more active deals: crossfade automatically, with dots.
  dotsWrap.classList.add("show");
  dotsWrap.innerHTML = active.map(function (_, i) {
    return '<button class="deal-dot' + (i === 0 ? " active" : "") +
           '" data-index="' + i + '" aria-label="Show deal ' + (i + 1) + '"></button>';
  }).join("");

  const dots = dotsWrap.querySelectorAll(".deal-dot");
  let current = 0;
  let timer = null;

  function goTo(index) {
    imgs[current].classList.remove("active");
    btns[current].classList.remove("active");
    dots[current].classList.remove("active");
    current = index;
    imgs[current].classList.add("active");
    btns[current].classList.add("active");
    dots[current].classList.add("active");
  }
  function startAutoplay() {
    timer = setInterval(function () { goTo((current + 1) % imgs.length); }, 4500);
  }
  function stopAutoplay() {
    clearInterval(timer);
  }

  dots.forEach(function (dot) {
    dot.addEventListener("click", function () {
      stopAutoplay();
      goTo(parseInt(dot.dataset.index, 10));
      startAutoplay();
    });
  });

  slider.addEventListener("mouseenter", stopAutoplay);
  slider.addEventListener("mouseleave", startAutoplay);

  startAutoplay();
};


  window.addEventListener('load', function(){
    var loader = document.getElementById('pageLoader');
    if(loader){
      setTimeout(function(){
        loader.classList.add('loader-hidden');
        document.body.classList.remove('is-loading');
      }, 400); // thora delay taake animation smooth mehsoos ho, chahein to 0 kar dein
    }
  });
